# Project information
site_name: Monero Documentation
site_description: 'Unofficial but soon to be Offical Monero Documentation'
site_author: "dan-is-not-the-man"
site_url: 'http://localhost'
site_dir: 'public'

copyright: '© 2024 Monero Community <a href="https://opensource.org/licenses/MIT">MIT</a>'

nav:
- Home: 'index.md'
- Interacting:
  - Download: 'interacting/download-monero-binaries.md'
  - Verify: 'interacting/verify-monero-binaries.md'
  - Overview: 'interacting/overview.md'
  - Config file: 'interacting/monero-config-file.md'
  - monerod: 'interacting/monerod-reference.md'
  - monero-wallet-cli: 'interacting/monero-wallet-cli-reference.md'
  - monero-wallet-gui: 'interacting/monero-wallet-gui-reference.md'
  - monero-wallet-rpc: 'interacting/monero-wallet-rpc-reference.md'
  - monero-blockchain-export: 'interacting/monero-blockchain-export-reference.md'
  - monero-blockchain-import: 'interacting/monero-blockchain-import-reference.md'
- Technical specs: 'technical-specs.md'
- Cryptography:
    - Introduction: 'cryptography/introduction.md'
    - Asymmetric:
      - Introduction: 'cryptography/asymmetric/introduction.md'
      - Private keys: 'cryptography/asymmetric/private-key.md'
      - Public keys: 'cryptography/asymmetric/public-key.md'
      - Edwards25519 curve: 'cryptography/asymmetric/edwards25519.md'
      - Key image: 'cryptography/asymmetric/key-image.md'
    - Base58: 'cryptography/base58.md'
    - PRNG: 'cryptography/prng.md'
    - 'Keccak-256': 'cryptography/keccak-256.md'
- Address:
    - Standard: 'public-address/standard-address.md'
    - Subaddress: 'public-address/subaddress.md'
    - Integrated: 'public-address/integrated-address.md'
- Proof of Work:
    - What is PoW?: 'proof-of-work/what-is-pow.md'
    - PoW in Cryptocurrencies: 'proof-of-work/pow-in-cryptocurrencies.md'
    - CryptoNight: 'proof-of-work/cryptonight.md'
    - RandomX: 'proof-of-work/random-x.md'
- Multisignature: 'multisignature.md'
- Infrastructure:
    - Mainnet, stagenet, testnet: 'infrastructure/networks.md'
    - Tor onion seed nodes: 'infrastructure/tor-onion-p2p-seed-nodes.md'
    - MoneroPulse: 'infrastructure/monero-pulse.md'
- Running a Node:
  # - On your Laptop: 'localhost-node.md'
  # - Remote Node: 'remote-node.md'
  # - Open Remote Node: 'open-remote-node.md'
  - Open Node + Tor Onion: 'running-node/open-node-tor-onion.md'
- Cold storage:
    - Offline Transaction Signing: 'cold-storage/offline-transaction-signing.md'
- Accepting Monero:
    - Overview: 'accepting-monero/overview.md'

docs_dir: docs/
exclude_docs: overrides/

theme:
  name: material
  custom_dir: docs/overrides
  font:
    code: Roboto Mono


  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: logo
  logo: 'assets/monero-symbol-on-white-1280.png'

extra_css: ['overrides.css']

repo_name: 'dan-is-not-the-man/monerodocs'
repo_url: 'https://github.com/dan-is-not-the-man/monerodocs'

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - abbr
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true         # build time highlighting, not client side
  - pymdownx.inlinehilite
  - pymdownx.superfences         # nest code blocks inside codeblocks
  - pymdownx.snippets            # insert content from other files

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - i18n:
      fallback_to_default: true
      docs_structure: folder
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Sommaire
            Accepting Monero: Acceptation de Monero
            Interacting: Interaction
            Technical specs: Caractéristiques techniques
            Cryptography: Cryptographie
            Address: Adresse
            Proof of Work: Preuve de travail
            Multisignature: Multisignature
            Infrastructure: Infrastructure
            Running a Node: Courir un nœud
            Cold storage: Stockage à froid
 # - git-revision-date-localized:
 #      fallback_to_build_date: true

extra:
  version:
    provider: mike
  generator: false
